{
 "title": "FLASK_MONITORING",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "All Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(http_errors_total[1m]) ", "legendFormat": "__auto" },
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(http_errors_total[1m]) ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(http_requests_total[1m]) ", "legendFormat": "__auto" }
   ]
  }
 ]
}